### ISSUE TITLE
attempt number is added to screenshot name, causing retries of failures to inappropriately succeed

### ISSUE THREAD

**Issue by froodian** [FRSOURCE/cypress-plugin-visual-regression-diff#168] opened 2022-11-02 19:16 UTC
**Describe the bug**
Similar to https://github.com/meinaart/cypress-plugin-snapshots/issues/217 (and the [open pull](https://github.com/meinaart/cypress-plugin-snapshots/pull/218/files) that fixes it), `cy.state('runnable')._currentRetry` (as documented [here](https://docs.cypress.io/guides/guides/test-retries#Can-I-access-the-current-attempt-counter-from-the-test)) should be incorporated into the nameCacheCounter logic so that a retried test is not seen as a new test.

**To Reproduce**
1. Have a test, with an accepted and committed baseline image
2. Have `retries` enabled in the cypress config ([docs](https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries))
3. Change the code under test so that the test will go red
4. Run the test

**Expected behavior**
Test should go red. Instead test goes red, then on retry it goes green because the plugin is generating an actual with `#1.png` in the name instead of `#0.png` and therefore treating it as a new test.

**Screenshots**
<img width="651" alt="image" src="https://user-images.githubusercontent.com/1547435/199581074-3305e024-7afb-431b-92fe-93934987c399.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1547435/199581531-ecdc06eb-357e-4ca7-880d-98dd98b5fb52.png">

**Please complete the following information:**
 - Mac OS 12.6
 - Chrome 107
 - Cypress 10.8.0

**Additional context**

**Comment by FRSgit** [comment] 2022-11-03 11:58
Hey @froodian,

First of all - thank you for such detailed issue! ❤️  I never have used Cypress retries option, so you description made it much, much easier for me to understand what's the issue and how it can be covered.
I've just merged a PR that should cover your case (see #171). The implementation is slightly different than the one from cypress-plugin-snapshots (I do not use separated map for retries tracking), but I think it will do.

Please try the new release 3.1.0 and come back with a feedback (simple "it works!" is enough 😄 )

**Comment by froodian** [comment] 2022-11-03 16:48
Hi @FRSgit - thanks for the fast fix!

It looks like with 3.1.0, it mostly works - but, if the first attempt fails for unrelated reasons (before the screenshot), the retry attempt creates `Rendered IAM HTML Built Via Grapes DnD HTML IAM Composer Rendered IAM #-1.png` (instead of #0 as would be expected), and so still goes green when the screenshot comparison should fail.  

I think this could be fixed by either making the code more like

```
  if (typeof nameCacheCounter[screenshotPath] === "undefined") {
    nameCacheCounter[screenshotPath] = -1;
  } else if (currentRetryNumber > 0) {
   // it's a retry of the same image that was run previously, so let's decrease the counter
    --nameCacheCounter[screenshotPath];
  }
```

- or by testing to make sure `nameCacheCounter[screenshotPath]` doesn't go below -1?

**Comment by FRSgit** [comment] 2022-11-03 21:51
Hey @froodian,

You're right - this condition is not enough. But after giving it a though solution proposed by you (and the implementation for `cypress-plugin-snapshots`) also does not cover all of the cases. For example this won't work when there were more than 2 screenshots done before test fail & retry, because we're now decreasing nameCacheCounter only by one. Also - what if names of screenshots done before retry were different?

I need to think about it for a moment, if you have any ideas - don't hesitate to post them here

**Closed** 2022-11-04 00:38 UTC
Labels: bug, good first issue, released

**Comment by FRSgit** [comment] 2022-11-04 00:57
Just released 3.1.1 which should handle all of the cases above correctly. Please give it a go 🙏

**Comment by FRSgit** [comment] 2022-11-04 22:57
Cool, thanks for retesting it! ✌️

**Comment by mduivcap** [comment] 2023-07-18 11:21
If it's always #0, why do we even need a number? I just started to use this plugin but I noticed that suddenly during one of the runs #1 image was added and I don't know why (pretty new to Cypress and this plugin). I'm not aware of any retry that I configured. And I was confused since this is the base image (which should only exist once).
I'm using:

- node: v19.3.0
- cypress: 12.17.1
- cypress-plugin-visual-regression-diff: 3.3.10

Not sure how to reproduce this, since it only happened once. I was just playing around with the settings (threshold) and running the base against different browser. If I have a reproduce path I'll let you know, but I think this issue is not resolved completely yet.

**Comment by gigaSproule** [comment] 2023-10-02 13:45
I'm seeing this issue still, but only with `cypress open`, not with `cypress run`. It seems that when a file diff is large enough, it creates a new screenshot, which seems to trigger a new run of the tests, which then pass.

It's odd, because if I run the test in a different browser, I get an image diff of `0.12`, which fails as my max is set to `0.01` and that's ok. When I change something big (such as the background colour), the diff is `0.99`, and that's when I'm seeing the multiple images. Weirdly, it gets up to `#7` and then stops.

I've got `retries` set to `0` and `watchForFileChanges` set to `false`.

This is the same whether I run it directly on the mac or via docker.

node: v18.18.0
cypress: 13.2.0
cypress-plugin-visual-regression-diff: 3.3.10
